name: Testing GH Actions

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: "AppajiC"
          reaction: rocket
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  
  after-deploy:
    runs-on: ubuntu-latest
    needs: [deploy]
    if: steps.check.outputs.triggered == 'true'
    steps:
      - name: True Comment
        uses: unsplash/comment-on-pr@master
        with:
          msg: "Trigger Present"
          check_for_duplicate_msg: false
    if: steps.check.outputs.triggered != 'true'
    steps:
      - name: False Comment
        uses: unsplash/comment-on-pr@master
        with:
          msg: "Trigger Absent"
          check_for_duplicate_msg: false