name: Testing GH Actions

on:
  pull_request:
    types: [opened]

jobs:
  env:
    BUILD_DOCS: "false"
    GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger
        uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: "AppajiC"
          reaction: rocket
        if: steps.check.outputs.triggered == 'true'
        env:          
          BUILD_DOCS: "true"
  job_2:
    name: Sample_Comment
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR
        run: "echo ${env.BUILD_DOCS}"
        # if: env.BUILD_DOCS == 'true':
        # with:
        #   msg: "Your comment has AppajiC word"
        #   check_for_duplicate_msg: false
        # if: env.BUILD_DOCS != 'true':
        # with:
        #   msg: "Your comment doesn't have AppajiC word"
        #   check_for_duplicate_msg: false
