name: Testing GH Actions

on:
  pull_request:
    types: [opened]

jobs:
  env:
    BUILD_DOCS: "false"
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger's with AppajiC
      uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: "AppajiC"
          reaction: rocket
        if: steps.check.outputs.triggered == 'true'
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          BUILD_DOCS: "true"
  job_2:
    name: Sample-Comment
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR
      uses: unsplash/comment-on-pr@master
      env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      if: ${{env.BUILD_DOCS}} == 'true':
      with:
        msg: "Your comment has AppajiC word"
        check_for_duplicate_msg: false
      if: ${{env.BUILD_DOCS}} != 'true':
      with:
        msg: "Your comment doesn't have AppajiC word"
        check_for_duplicate_msg: false
