name: Testing GH Actions

on:
  pull_request:
    types: [opened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: "AppajiC"
          reaction: rocket
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - run: "echo Found it!"
        if: steps.check.outputs.triggered == 'true'
      - uses: unsplash/comment-on-pr@master
        name: comment PR
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        - with:
          msg: "Trigger Present"
          check_for_duplicate_msg: false  # OPTIONAL 
        if : steps.check.outputs.triggered == 'true'
        - with:
          msg: "Trigger Absent"
          check_for_duplicate_msg: false  # OPTIONAL 
        if : steps.check.outputs.triggered != 'true'

